import type { Metadata } from 'next';
import './globals.css';
import { Source_Sans_3 } from 'next/font/google';

const sans = Source_Sans_3({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ja'>
			<body className={`${sans.className} bg-black text-white`}>
				<div>{children}</div>
			</body>
		</html>
	);
}
